### PR TITLE
Moment JS + timezone

### PR DESCRIPTION
**Pull request by kunagpal**

### CODE REVIEW

**Comment by kunagpal** [comment]
@shamasis Tests have been fixed.

**Comment by kunagpal** [comment]
@shamasis The `moment().calendar()` method hooks onto the current time by default, which causes tests to become time-bound. Adding a time reference parameter to it solved the issue.

**Comment by czardoz** [comment]
@kunagpal Let's do a memory profiling again on monday, and see how it goes.

**Comment by kunagpal** [comment]
@czardoz Roger that.

**Comment by kunagpal** [comment]
Closing in favour of #122

**Pull request closed without merging**
