### PR TITLE
Update `lodash` to `4.17.4`

### PR DESCRIPTION
**Pull request by kamalaknn**

### CODE REVIEW

**Comment by kunagpal** [comment]
@kamalaknn Could you also send another P.R to update sandbox docs?

**Comment by kamalaknn** [comment]
@kunagpal could you point where to find the docs? Are you talking about the sandbox libraries wiki?

**Comment by kunagpal** [comment]
@kamalaknn Yes, it's in https://github.com/postmanlabs/postman-docs

**Comment by kamalaknn** [comment]
@kunagpal creating a task to track this. Will update when App and `newman` go out.

**Pull request merged**
