### PR TITLE
Renamed prepublish script to prepublishOnly

### PR DESCRIPTION
**Pull request by kunagpal**
https://docs.npmjs.com/misc/scripts#deprecation-note

```
PREPUBLISH AND PREPARE

DEPRECATION NOTE

Since npm@1.1.71, the npm CLI has run the prepublish script for both npm publish and npm install, because it's a convenient way to prepare a package for use (some common use cases are described in the section below). It has also turned out to be, in practice, very confusing. As of npm@4.0.0, a new event has been introduced, prepare, that preserves this existing behavior. A new event, prepublishOnly has been added as a transitional strategy to allow users to avoid the confusing behavior of existing npm versions and only run on npm publish (for instance, running the tests one last time to ensure they're in good shape).

See https://github.com/npm/npm/issues/10074 for a much lengthier justification, with further reading, for this change.

USE CASES

If you need to perform operations on your package before it is used, in a way that is not dependent on the operating system or architecture of the target system, use a prepublish script. This includes tasks such as:

Compiling CoffeeScript source code into JavaScript.
Creating minified versions of JavaScript source code.
Fetching remote resources that your package will use.
The advantage of doing these things at prepublish time is that they can be done once, in a single place, thus reducing complexity and variability. Additionally, this means that:

You can depend on coffee-script as a devDependency, and thus your users don't need to have it installed.
You don't need to include minifiers in your package, reducing the size for your users.
You don't need to rely on your users having curl or wget or other system tools on the target machines.
```

### CODE REVIEW

**Comment by shamasis** [comment]
@czardoz - is this our use case for cache script?

**Comment by kunagpal** [comment]
@czardoz

**Comment by czardoz** [comment]
Totally not sure about this change.

**Comment by czardoz** [comment]
@kunagpal Maybe we should call it `prepare`?

**Comment by kunagpal** [comment]
@czardoz `prepare` is available in npm `v4.x` :/

**Comment by kunagpal** [comment]
@shamasis Ping

**Pull request closed without merging**
